# Generated by Django 4.1.7 on 2023-04-25 18:33

from django.db import migrations, models
import django.db.models.deletion
import goal_predictor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('info', models.JSONField(default=dict)),
                ('roster', models.JSONField(default=dict)),
                ('schedule', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
                ('rankings', models.JSONField(default=dict)),
                ('season', models.CharField(default='20222023', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('info', models.JSONField(default=dict)),
                ('position', models.CharField(max_length=10)),
                ('game_log', models.JSONField(default=dict)),
                ('season_stats', models.JSONField(default=dict)),
                ('day_stats', models.JSONField(default=dict)),
                ('week_stats', models.JSONField(default=dict)),
                ('mon_stats', models.JSONField(default=dict)),
                ('div_stats', models.JSONField(default=dict)),
                ('league_stats', models.JSONField(default=dict)),
                ('home_away_stats', models.JSONField(default=dict)),
                ('w_l_stats', models.JSONField(default=dict)),
                ('sit_goals', models.JSONField(default=dict)),
                ('season_pace', models.JSONField(default=dict)),
                ('schedule', models.JSONField(default=dict)),
                ('season', models.CharField(default=goal_predictor.models.get_current_season, max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.team')),
            ],
        ),
    ]
