# Generated by Django 4.1.7 on 2023-04-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nhl_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=10)),
                ('info', models.JSONField(default=dict)),
                ('season', models.CharField(default='20222023', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nhl_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('info', models.JSONField(default=dict)),
                ('roster', models.JSONField(default=dict)),
                ('schedule', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
                ('rankings', models.JSONField(default=dict)),
                ('season', models.CharField(default='20222023', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWinSplits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWeekSplits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSitGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonPace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMonSplits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLeagueStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHomeSplits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('time_on_ice', models.DurationField()),
                ('assists', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('pim', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('games', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('power_play_goals', models.IntegerField()),
                ('power_play_points', models.IntegerField()),
                ('power_play_time_on_ice', models.DurationField()),
                ('even_time_on_ice', models.DurationField()),
                ('penalty_minutes', models.IntegerField()),
                ('faceoff_pct', models.FloatField()),
                ('shot_pct', models.FloatField()),
                ('game_winning_goals', models.IntegerField()),
                ('overtime_goals', models.IntegerField()),
                ('shorthanded_goals', models.IntegerField()),
                ('shorthanded_points', models.IntegerField()),
                ('shorthanded_time_on_ice', models.DurationField()),
                ('blocked', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('points', models.IntegerField()),
                ('shifts', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=50)),
                ('opponent_id', models.IntegerField()),
                ('opponent_name', models.CharField(max_length=50)),
                ('game_id', models.IntegerField()),
                ('game_link', models.URLField()),
                ('date', models.DateField()),
                ('is_home', models.BooleanField()),
                ('is_win', models.BooleanField()),
                ('is_ot', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDivSplits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDaySplits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=8)),
                ('data', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal_predictor.team'),
        ),
    ]
