# Generated by Django 4.1.7 on 2023-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamelog',
            name='even_time_on_ice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playergamelog',
            name='power_play_time_on_ice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playergamelog',
            name='shorthanded_time_on_ice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playergamelog',
            name='time_on_ice',
            field=models.IntegerField(),
        ),
    ]
