# Generated by Django 4.1.7 on 2023-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nhl_id',
            field=models.IntegerField(default=0),
        ),
    ]
