# Generated by Django 4.1.7 on 2023-04-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_predictor', '0002_alter_playergamelog_even_time_on_ice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamelog',
            name='faceoff_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playergamelog',
            name='shot_pct',
            field=models.FloatField(null=True),
        ),
    ]
