# Generated by Django 4.1.7 on 2023-04-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_predictor', '0004_remove_playerseasonstats_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerseasonstats',
            options={'verbose_name_plural': 'player season stats'},
        ),
    ]
