# Generated by Django 4.1.7 on 2023-05-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_predictor', '0005_alter_playerseasonstats_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstats',
            name='assists',
            field=models.IntegerField(default=0),
        ),
    ]
